### ISSUE TITLE
Missing chef-server-ctl upgrade

### ISSUE THREAD

**Issue by e100** [opscode-cookbooks/chef-server#61]
The official instructions say to run "chef-server-ctl upgrade" when upgrading.
http://docs.getchef.com/open_source/upgrade_server_open_source.html#upgrade-to-chef-server-osc-11-1-4-or-higher

This cookbook only runs "chef-server-ctl reconfigure"

**Comment by jtimberman** [comment]
That's by design. Upgrades of the Chef Server are special and require careful consideration, as there may be schema updates, or other steps. Doing that automatically can be [surprising/undesired](https://github.com/opscode-cookbooks/chef-server/issues/66). This is especially true for upgrades between major versions.

For example, we have [detailed documentation](https://docs.chef.io/upgrade_server.html) for upgrading from 11 to 12.
